# Assignment 1: Numpy

Perform the follwing tasks:


In [45]:
#3.1: import the numpy library
import numpy as np

In [46]:
#3.2: create a random 10x10 array named A (rowsxcolumns)
A = np.random.randn(10,10)
A

array([[-1.769982  , -1.67877542,  0.59767299, -0.03920971,  0.16423393,
         1.0508426 , -1.03261178, -0.55580762,  1.47034606,  0.29349302],
       [ 1.09097872,  1.40575197, -0.46847898,  0.90290084, -0.52963811,
        -0.60575066, -0.12185827, -0.31331235,  0.77118302,  1.46166876],
       [-1.0274653 , -0.01542327, -0.72595233, -0.48459747,  1.05939452,
        -0.03627075, -0.84448918,  0.34513475, -0.97601743,  0.03072474],
       [ 0.27540621, -0.02653085,  0.15777723, -1.6043039 , -0.36252495,
         0.53801569,  0.17213029,  0.38393636, -1.3751062 , -0.79970025],
       [ 0.30970368, -0.18294179,  1.90419566, -0.67841761, -0.02113081,
        -0.16854014,  1.41126393, -0.23285247,  0.65856842,  0.94204064],
       [ 1.12641225, -0.40321787,  1.84354631, -0.19688139, -0.89665055,
         1.15880905, -1.2761617 , -0.25035692, -0.14020895, -0.05716007],
       [-0.19014317,  0.64002625,  0.54754654,  0.5357726 , -0.07279662,
        -1.64666901, -0.7176646 , -0.70647214

In [47]:
#3.3: return only the odd rows of Aodd
odd_row_indices = [1,3,5,7,9]
A[odd_row_indices]



array([[ 1.09097872,  1.40575197, -0.46847898,  0.90290084, -0.52963811,
        -0.60575066, -0.12185827, -0.31331235,  0.77118302,  1.46166876],
       [ 0.27540621, -0.02653085,  0.15777723, -1.6043039 , -0.36252495,
         0.53801569,  0.17213029,  0.38393636, -1.3751062 , -0.79970025],
       [ 1.12641225, -0.40321787,  1.84354631, -0.19688139, -0.89665055,
         1.15880905, -1.2761617 , -0.25035692, -0.14020895, -0.05716007],
       [-0.89315348, -0.36720459, -0.11157609, -0.63935302, -1.18481875,
        -0.46548076, -0.70771509,  3.21151965, -1.84701118,  0.19563975],
       [ 2.68959213, -0.46568546, -0.67558327, -0.97851969, -1.43228406,
        -1.18984694, -1.14056319, -0.06302418,  0.92465461, -0.63377174]])

In [48]:
shape_A = A.shape
shape_A
A[0]




array([-1.769982  , -1.67877542,  0.59767299, -0.03920971,  0.16423393,
        1.0508426 , -1.03261178, -0.55580762,  1.47034606,  0.29349302])

In [49]:
#alternative
row_indices_A = np.arange(0,shape_A[1],1)#get the indices of A
mask_A = (row_indices_A % 2) > 0 #get a mask of the odd indices
A[mask_A]

array([[ 1.09097872,  1.40575197, -0.46847898,  0.90290084, -0.52963811,
        -0.60575066, -0.12185827, -0.31331235,  0.77118302,  1.46166876],
       [ 0.27540621, -0.02653085,  0.15777723, -1.6043039 , -0.36252495,
         0.53801569,  0.17213029,  0.38393636, -1.3751062 , -0.79970025],
       [ 1.12641225, -0.40321787,  1.84354631, -0.19688139, -0.89665055,
         1.15880905, -1.2761617 , -0.25035692, -0.14020895, -0.05716007],
       [-0.89315348, -0.36720459, -0.11157609, -0.63935302, -1.18481875,
        -0.46548076, -0.70771509,  3.21151965, -1.84701118,  0.19563975],
       [ 2.68959213, -0.46568546, -0.67558327, -0.97851969, -1.43228406,
        -1.18984694, -1.14056319, -0.06302418,  0.92465461, -0.63377174]])

In [50]:
#3.4: perform a matrix multiplication of A with it's transposed
np.dot(A,A.T)

array([[11.06438143, -3.46701826,  0.81961486, -2.42761725,  0.65999481,
         2.09720392,  0.96424321, -2.24055088,  0.07331699, -3.44338724],
       [-3.46701826,  7.69273892, -2.49220448, -3.76379537,  0.4751844 ,
        -0.5641337 ,  4.34709002, -3.16451188, -4.93749433,  3.1374295 ],
       [ 0.81961486, -2.49220448,  4.72723065,  1.2814752 , -3.27124974,
        -2.2595986 , -1.27951264,  3.5906592 ,  0.0183576 , -3.24635807],
       [-2.42761725, -3.76379537,  1.2814752 ,  5.80359586, -0.10947307,
         1.79888742, -4.38572989,  4.44554834,  2.19120912,  1.11022547],
       [ 0.65999481,  0.4751844 , -3.27124974, -0.10947307,  7.61148704,
         2.00141218,  1.47106751, -2.66332758,  0.78291011, -1.05667631],
       [ 2.09720392, -0.5641337 , -2.2595986 ,  1.79888742,  2.00141218,
         8.72982821, -0.53263681, -0.06793204,  1.15080779,  3.44790158],
       [ 0.96424321,  4.34709002, -1.27951264, -4.38572989,  1.47106751,
        -0.53263681,  6.83976731, -3.44999361

In [51]:
#3.5: compute the matrix inverse of A
np.linalg.inv(A)


array([[-2.07329462e-01,  3.14347951e-02,  2.50590111e-01,
        -3.54605200e-01,  1.78115208e-01,  1.68537937e-01,
        -2.92927971e-01, -5.83411416e-02,  3.41349106e-02,
         2.19271451e-01],
       [ 4.95627423e-01,  1.22546683e+00, -2.85825406e-01,
         1.43312038e+00, -4.10816472e-01, -2.99980705e-01,
         6.77373808e-01,  7.43515735e-03,  7.28396502e-01,
        -2.93264569e-01],
       [-2.63509640e-02, -2.89596592e-02, -6.59335445e-02,
         1.14745133e-01,  9.52497711e-02,  1.98265514e-01,
         3.08700728e-01,  3.96154616e-02,  1.69215480e-01,
        -1.22393366e-01],
       [-4.02677063e-01, -5.27614026e-01, -1.49019585e-01,
        -8.87295239e-01, -1.10909354e-01,  2.67874363e-01,
        -1.91942938e-01,  2.08546596e-02, -2.52651784e-01,
        -9.19973766e-02],
       [ 8.33097097e-02,  3.69818907e-01,  6.00759862e-01,
         4.04364324e-03,  1.68096948e-01, -6.37723270e-02,
         1.23733042e-02, -9.43072145e-02,  4.48738085e-01,
         5.

In [52]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )

In [53]:
B=np.array(A) #create a copy of A to compare it later
mask = A>0.5
indices = np.where(mask)
A[indices]

array([0.59767299, 1.0508426 , 1.47034606, 1.09097872, 1.40575197,
       0.90290084, 0.77118302, 1.46166876, 1.05939452, 0.53801569,
       1.90419566, 1.41126393, 0.65856842, 0.94204064, 1.12641225,
       1.84354631, 1.15880905, 0.64002625, 0.54754654, 0.5357726 ,
       1.2058698 , 0.78869149, 3.21151965, 0.83936081, 1.03023804,
       0.6705212 , 0.72338771, 0.64974445, 2.68959213, 0.92465461])

In [54]:
A[indices]=A[indices]/2
A[indices]

array([0.29883649, 0.5254213 , 0.73517303, 0.54548936, 0.70287599,
       0.45145042, 0.38559151, 0.73083438, 0.52969726, 0.26900784,
       0.95209783, 0.70563197, 0.32928421, 0.47102032, 0.56320613,
       0.92177316, 0.57940452, 0.32001312, 0.27377327, 0.2678863 ,
       0.6029349 , 0.39434575, 1.60575982, 0.4196804 , 0.51511902,
       0.3352606 , 0.36169386, 0.32487223, 1.34479606, 0.46232731])

In [55]:
A

array([[-1.769982  , -1.67877542,  0.29883649, -0.03920971,  0.16423393,
         0.5254213 , -1.03261178, -0.55580762,  0.73517303,  0.29349302],
       [ 0.54548936,  0.70287599, -0.46847898,  0.45145042, -0.52963811,
        -0.60575066, -0.12185827, -0.31331235,  0.38559151,  0.73083438],
       [-1.0274653 , -0.01542327, -0.72595233, -0.48459747,  0.52969726,
        -0.03627075, -0.84448918,  0.34513475, -0.97601743,  0.03072474],
       [ 0.27540621, -0.02653085,  0.15777723, -1.6043039 , -0.36252495,
         0.26900784,  0.17213029,  0.38393636, -1.3751062 , -0.79970025],
       [ 0.30970368, -0.18294179,  0.95209783, -0.67841761, -0.02113081,
        -0.16854014,  0.70563197, -0.23285247,  0.32928421,  0.47102032],
       [ 0.56320613, -0.40321787,  0.92177316, -0.19688139, -0.89665055,
         0.57940452, -1.2761617 , -0.25035692, -0.14020895, -0.05716007],
       [-0.19014317,  0.32001312,  0.27377327,  0.2678863 , -0.07279662,
        -1.64666901, -0.7176646 , -0.70647214

In [56]:
B

array([[-1.769982  , -1.67877542,  0.59767299, -0.03920971,  0.16423393,
         1.0508426 , -1.03261178, -0.55580762,  1.47034606,  0.29349302],
       [ 1.09097872,  1.40575197, -0.46847898,  0.90290084, -0.52963811,
        -0.60575066, -0.12185827, -0.31331235,  0.77118302,  1.46166876],
       [-1.0274653 , -0.01542327, -0.72595233, -0.48459747,  1.05939452,
        -0.03627075, -0.84448918,  0.34513475, -0.97601743,  0.03072474],
       [ 0.27540621, -0.02653085,  0.15777723, -1.6043039 , -0.36252495,
         0.53801569,  0.17213029,  0.38393636, -1.3751062 , -0.79970025],
       [ 0.30970368, -0.18294179,  1.90419566, -0.67841761, -0.02113081,
        -0.16854014,  1.41126393, -0.23285247,  0.65856842,  0.94204064],
       [ 1.12641225, -0.40321787,  1.84354631, -0.19688139, -0.89665055,
         1.15880905, -1.2761617 , -0.25035692, -0.14020895, -0.05716007],
       [-0.19014317,  0.64002625,  0.54754654,  0.5357726 , -0.07279662,
        -1.64666901, -0.7176646 , -0.70647214