# Assignment 1: Numpy

Perform the follwing tasks:


In [3]:
#3.1: import the numpy library
import numpy as np

In [4]:
#3.2: create a random 10x10 array named A (rowsxcolumns)
A = np.random.randn(10,10)
A

array([[-0.06736765,  1.55640919,  0.20909466, -0.73977693, -0.54905949,
        -2.08563782,  1.01911105, -1.47279172,  1.27459076,  0.46139812],
       [-1.09859541, -0.709155  , -0.00847697, -0.47907694,  1.00425387,
         1.01107146, -0.50376683,  1.55020734,  0.80530167, -0.90044761],
       [ 0.93477656, -0.58717959, -0.31026116,  1.03181059, -0.7041117 ,
         1.06266309, -0.78925619, -0.3246525 ,  0.8153638 , -1.40554301],
       [-0.36493589, -1.33866437,  0.07988358,  0.14961745,  0.85314333,
         0.25398962,  0.83216677, -0.13707288, -0.20740284, -0.66296362],
       [ 0.45170885,  0.7809587 ,  1.33235789,  1.11125332, -0.30122125,
         1.34605779,  0.03753233, -0.47744693, -0.35023454,  1.44920191],
       [-0.44684713, -0.63884154, -0.0953949 ,  0.3694629 ,  1.86298121,
        -1.9025224 , -0.88857381,  0.38135832,  0.73040778,  0.7520958 ],
       [ 0.73237028, -1.2133918 , -0.19217637,  0.21863973,  1.2322968 ,
        -1.06599015, -1.07724776, -1.11210345

In [5]:
#3.3: return only the odd rows of Aodd
odd_row_indices = [1,3,5,7,9]
A[odd_row_indices]



array([[-1.09859541, -0.709155  , -0.00847697, -0.47907694,  1.00425387,
         1.01107146, -0.50376683,  1.55020734,  0.80530167, -0.90044761],
       [-0.36493589, -1.33866437,  0.07988358,  0.14961745,  0.85314333,
         0.25398962,  0.83216677, -0.13707288, -0.20740284, -0.66296362],
       [-0.44684713, -0.63884154, -0.0953949 ,  0.3694629 ,  1.86298121,
        -1.9025224 , -0.88857381,  0.38135832,  0.73040778,  0.7520958 ],
       [-0.29478191,  1.69919436, -0.52143947, -0.60030268,  0.83465127,
        -0.18607206,  1.59782013,  1.13480524,  0.32032388, -0.1386909 ],
       [ 1.29961893,  1.00899495,  1.1376136 ,  0.2487309 ,  0.37879264,
        -0.38520635, -1.95075987,  1.10920158, -0.67158717, -0.52191186]])

In [6]:
shape_A = A.shape
shape_A
A[0]




array([-0.06736765,  1.55640919,  0.20909466, -0.73977693, -0.54905949,
       -2.08563782,  1.01911105, -1.47279172,  1.27459076,  0.46139812])

In [7]:
#alternative
row_indices_A = np.arange(0,shape_A[1],1)#get the indices of A
mask_A = (row_indices_A % 2) > 0 #get a mask of the odd indices
A[mask_A]

array([[-1.09859541, -0.709155  , -0.00847697, -0.47907694,  1.00425387,
         1.01107146, -0.50376683,  1.55020734,  0.80530167, -0.90044761],
       [-0.36493589, -1.33866437,  0.07988358,  0.14961745,  0.85314333,
         0.25398962,  0.83216677, -0.13707288, -0.20740284, -0.66296362],
       [-0.44684713, -0.63884154, -0.0953949 ,  0.3694629 ,  1.86298121,
        -1.9025224 , -0.88857381,  0.38135832,  0.73040778,  0.7520958 ],
       [-0.29478191,  1.69919436, -0.52143947, -0.60030268,  0.83465127,
        -0.18607206,  1.59782013,  1.13480524,  0.32032388, -0.1386909 ],
       [ 1.29961893,  1.00899495,  1.1376136 ,  0.2487309 ,  0.37879264,
        -0.38520635, -1.95075987,  1.10920158, -0.67158717, -0.52191186]])

In [8]:
#3.4: perform a matrix multiplication of A with it's transposed
np.dot(A,A.T)

array([[12.7144625 , -5.52277363, -3.57023408, -2.67135553, -1.03674774,
         1.4983925 ,  0.82390101,  3.23068061,  0.90878343, -2.58633026],
       [-5.52277363,  8.08643109,  1.08164901,  2.18968889, -2.88130236,
         1.66486359,  0.7565249 ,  1.39803077, -3.7581743 ,  0.35018344],
       [-3.57023408,  1.08164901,  7.37320215,  0.39411557,  0.14230475,
        -2.84931311,  3.26789571, -3.68971362, -1.2082552 ,  1.21554698],
       [-2.67135553,  2.18968889,  0.39411557,  3.94015874, -1.64414048,
         0.73027534,  1.89525146, -0.43411513,  0.28168215, -2.76166739],
       [-1.03674774, -2.88130236,  0.14230475, -1.64414048,  8.17881934,
        -2.92066555, -3.86716179, -1.46488474,  0.34250655,  1.41058975],
       [ 1.4983925 ,  1.66486359, -2.84931311,  0.73027534, -2.92066555,
         9.87782556,  5.38637578, -0.07424997, -0.8573763 ,  1.46993989],
       [ 0.82390101,  0.7565249 ,  3.26789571,  1.89525146, -3.86716179,
         5.38637578,  9.43665785, -3.57312437

In [9]:
#3.5: compute the matrix inverse of A
np.linalg.inv(A)


array([[-4.15429539e-01,  1.45901133e-01, -9.00386077e-02,
        -8.70224851e-01,  3.53604367e-01, -2.57122452e-01,
         9.16394405e-01,  6.23770588e-01,  6.89014030e-01,
        -2.82144260e-01],
       [ 1.64915017e-01, -2.55218684e-01,  1.44335944e-02,
         2.22970739e-01, -9.35739453e-02, -1.79979882e-02,
        -2.69275152e-01, -1.83583643e-02, -4.41117372e-01,
         2.67075132e-01],
       [ 3.76712609e-01,  3.56962669e-01, -1.87536073e-02,
         4.10272241e-01,  2.62098025e-01, -5.23905787e-02,
        -1.10939699e-01, -1.80775763e-01,  1.61927547e-01,
         2.71289881e-01],
       [ 2.00304616e-01, -4.57897605e-01,  6.68068405e-01,
         7.98149237e-01, -1.05466351e-01,  5.77875323e-01,
        -8.47082080e-01, -1.83856992e-01, -3.73750741e-01,
         2.48142663e-01],
       [-1.80147383e-01, -7.59132109e-02, -3.00758929e-01,
         1.04177952e-01,  1.42560356e-01, -5.11033186e-02,
         3.85717312e-01,  2.03713810e-01, -1.67585694e-01,
         2.

In [10]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )

In [11]:
B=np.array(A) #create a copy of A to compare it later
mask = A>0.5
indices = np.where(mask)
A[indices]

array([1.55640919, 1.01911105, 1.27459076, 1.00425387, 1.01107146,
       1.55020734, 0.80530167, 0.93477656, 1.03181059, 1.06266309,
       0.8153638 , 0.85314333, 0.83216677, 0.7809587 , 1.33235789,
       1.11125332, 1.34605779, 1.44920191, 1.86298121, 0.73040778,
       0.7520958 , 0.73237028, 1.2322968 , 1.07410951, 1.69919436,
       0.83465127, 1.59782013, 1.13480524, 0.73102303, 0.66234566,
       0.50557563, 1.29961893, 1.00899495, 1.1376136 , 1.10920158])

In [12]:
A[indices]=A[indices]/2
A[indices]

array([0.77820459, 0.50955552, 0.63729538, 0.50212693, 0.50553573,
       0.77510367, 0.40265083, 0.46738828, 0.51590529, 0.53133155,
       0.4076819 , 0.42657166, 0.41608339, 0.39047935, 0.66617894,
       0.55562666, 0.67302889, 0.72460096, 0.93149061, 0.36520389,
       0.3760479 , 0.36618514, 0.6161484 , 0.53705476, 0.84959718,
       0.41732563, 0.79891007, 0.56740262, 0.36551152, 0.33117283,
       0.25278782, 0.64980946, 0.50449747, 0.5688068 , 0.55460079])

In [13]:
A

array([[-0.06736765,  0.77820459,  0.20909466, -0.73977693, -0.54905949,
        -2.08563782,  0.50955552, -1.47279172,  0.63729538,  0.46139812],
       [-1.09859541, -0.709155  , -0.00847697, -0.47907694,  0.50212693,
         0.50553573, -0.50376683,  0.77510367,  0.40265083, -0.90044761],
       [ 0.46738828, -0.58717959, -0.31026116,  0.51590529, -0.7041117 ,
         0.53133155, -0.78925619, -0.3246525 ,  0.4076819 , -1.40554301],
       [-0.36493589, -1.33866437,  0.07988358,  0.14961745,  0.42657166,
         0.25398962,  0.41608339, -0.13707288, -0.20740284, -0.66296362],
       [ 0.45170885,  0.39047935,  0.66617894,  0.55562666, -0.30122125,
         0.67302889,  0.03753233, -0.47744693, -0.35023454,  0.72460096],
       [-0.44684713, -0.63884154, -0.0953949 ,  0.3694629 ,  0.93149061,
        -1.9025224 , -0.88857381,  0.38135832,  0.36520389,  0.3760479 ],
       [ 0.36618514, -1.2133918 , -0.19217637,  0.21863973,  0.6161484 ,
        -1.06599015, -1.07724776, -1.11210345

In [14]:
B

array([[-0.06736765,  1.55640919,  0.20909466, -0.73977693, -0.54905949,
        -2.08563782,  1.01911105, -1.47279172,  1.27459076,  0.46139812],
       [-1.09859541, -0.709155  , -0.00847697, -0.47907694,  1.00425387,
         1.01107146, -0.50376683,  1.55020734,  0.80530167, -0.90044761],
       [ 0.93477656, -0.58717959, -0.31026116,  1.03181059, -0.7041117 ,
         1.06266309, -0.78925619, -0.3246525 ,  0.8153638 , -1.40554301],
       [-0.36493589, -1.33866437,  0.07988358,  0.14961745,  0.85314333,
         0.25398962,  0.83216677, -0.13707288, -0.20740284, -0.66296362],
       [ 0.45170885,  0.7809587 ,  1.33235789,  1.11125332, -0.30122125,
         1.34605779,  0.03753233, -0.47744693, -0.35023454,  1.44920191],
       [-0.44684713, -0.63884154, -0.0953949 ,  0.3694629 ,  1.86298121,
        -1.9025224 , -0.88857381,  0.38135832,  0.73040778,  0.7520958 ],
       [ 0.73237028, -1.2133918 , -0.19217637,  0.21863973,  1.2322968 ,
        -1.06599015, -1.07724776, -1.11210345